declare var __DEV__: boolean
declare var __PROD__: boolean
declare var __VERSION__: string
declare namespace NodeJS {
    interface ProcessEnv {
        SHELL:string
        SESSION_MANAGER:string
        COLORTERM:string
        XDG_CONFIG_DIRS:string
        npm_package_devDependencies__types_node:string
        npm_package_main:string
        XDG_SESSION_PATH:string
        NVM_INC:string
        COREPACK_ENABLE_DOWNLOAD_PROMPT:string
        XDG_MENU_PREFIX:string
        TERM_PROGRAM_VERSION:string
        ICEAUTHORITY:string
        npm_package_scripts_install:string
        NODE:string
        npm_config_ignore_scripts:string
        LC_ADDRESS:string
        LC_NAME:string
        npm_package_private:string
        npm_package_dependencies_discord_js:string
        MEMORY_PRESSURE_WRITE:string
        npm_config_argv:string
        npm_config_bin_links:string
        DESKTOP_SESSION:string
        LC_MONETARY:string
        GTK_RC_FILES:string
        NO_AT_BRIDGE:string
        EDITOR:string
        XDG_SEAT:string
        PWD:string
        npm_config_save_prefix:string
        XDG_SESSION_DESKTOP:string
        LOGNAME:string
        XDG_SESSION_TYPE:string
        npm_package_dependencies__sern_publisher:string
        npm_package_readmeFilename:string
        SYSTEMD_EXEC_PID:string
        npm_package_scripts_build:string
        _:string
        XAUTHORITY:string
        VSCODE_GIT_ASKPASS_NODE:string
        npm_package_packageManager:string
        MOTD_SHOWN:string
        GTK2_RC_FILES:string
        HOME:string
        COREPACK_ROOT:string
        npm_config_version_git_tag:string
        LC_PAPER:string
        LANG:string
        npm_package_devDependencies_typescript:string
        XDG_CURRENT_DESKTOP:string
        npm_config_init_license:string
        npm_package_version:string
        MEMORY_PRESSURE_WATCH:string
        STARSHIP_SHELL:string
        WAYLAND_DISPLAY:string
        npm_config_version_commit_hooks:string
        GIT_ASKPASS:string
        XDG_SEAT_PATH:string
        INVOCATION_ID:string
        MANAGERPID:string
        INIT_CWD:string
        CHROME_DESKTOP:string
        STARSHIP_SESSION_KEY:string
        KDE_SESSION_UID:string
        npm_lifecycle_script:string
        npm_package_description:string
        NVM_DIR:string
        VSCODE_GIT_ASKPASS_EXTRA_ARGS:string
        XKB_DEFAULT_LAYOUT:string
        npm_config_version_tag_prefix:string
        npm_package_dependencies_kazagumo:string
        YARN_WRAP_OUTPUT:string
        XDG_SESSION_CLASS:string
        TERM:string
        LC_IDENTIFICATION:string
        npm_package_name:string
        npm_package_type:string
        USER:string
        VSCODE_GIT_IPC_HANDLE:string
        QT_WAYLAND_RECONNECT:string
        KDE_SESSION_VERSION:string
        PAM_KWALLET5_LOGIN:string
        npm_package_dependencies_dotenv:string
        DISPLAY:string
        npm_lifecycle_event:string
        SHLVL:string
        npm_config_version_git_sign:string
        NVM_CD_FLAGS:string
        npm_package_dependencies__sern_handler:string
        npm_config_version_git_message:string
        LC_TELEPHONE:string
        LC_MEASUREMENT:string
        XDG_VTNR:string
        XDG_SESSION_ID:string
        npm_config_user_agent:string
        npm_execpath:string
        XDG_RUNTIME_DIR:string
        npm_config_strict_ssl:string
        npm_package_scripts_commands_publish:string
        DEBUGINFOD_URLS:string
        LC_TIME:string
        BUN_INSTALL:string
        npm_package_keywords_1:string
        npm_package_scripts_dev:string
        npm_package_keywords_0:string
        npm_package_keywords_2:string
        XKB_DEFAULT_VARIANT:string
        VSCODE_GIT_ASKPASS_MAIN:string
        QT_AUTO_SCREEN_SCALE_FACTOR:string
        JOURNAL_STREAM:string
        XDG_DATA_DIRS:string
        GDK_BACKEND:string
        KDE_FULL_SESSION:string
        npm_package_scripts_start:string
        BROWSER:string
        PATH:string
        npm_package_dependencies_shoukaku:string
        ORIGINAL_XDG_CURRENT_DESKTOP:string
        DBUS_SESSION_BUS_ADDRESS:string
        KDE_APPLICATIONS_AS_SCOPE:string
        NVM_BIN:string
        MAIL:string
        npm_config_registry:string
        npm_config_ignore_optional:string
        npm_node_execpath:string
        LC_NUMERIC:string
        TERM_PROGRAM:string
        npm_config_init_version:string
    }
}
